-- MySQL Script generated by MySQL Workbench
-- Fri Aug 25 10:40:22 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema empresa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema empresa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empresa` DEFAULT CHARACTER SET utf8 ;
USE `empresa` ;

-- -----------------------------------------------------
-- Table `empresa`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`departamento` (
  `idDep` VARCHAR(10) NOT NULL,
  `nomeDep` VARCHAR(70) NOT NULL,
  `telefoneDep` VARCHAR(15) NULL,
  PRIMARY KEY (`idDep`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`funcionario` (
  `emailFun` VARCHAR(45) NOT NULL,
  `nomeFun` VARCHAR(70) NOT NULL,
  `telefoneFun` VARCHAR(15) NULL,
  `cargoFun` VARCHAR(45) NULL,
  `salarioFun` DOUBLE NULL,
  `idDep` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`emailFun`),
  INDEX `fk_funcionario_departamento_idx` (`idDep` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_departamento`
    FOREIGN KEY (`idDep`)
    REFERENCES `empresa`.`departamento` (`idDep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`usuario` (
  `emailFun` VARCHAR(45) NOT NULL,
  `senhaUsu` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`emailFun`),
  CONSTRAINT `fk_usuario_funcionario1`
    FOREIGN KEY (`emailFun`)
    REFERENCES `empresa`.`funcionario` (`emailFun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
